@startuml Cerrar Reserva
title Diagrama de Secuencia: Cerrar Reserva

actor Cliente as user
participant "GestorDeReservas" as gR
participant "Reserva" as res
participant "GestorDeTemporada" as gT
participant "GestorKilometraje" as gK
participant "VehiculoMantenimiento" as vMant
participant "Vehiculo" as veh
participant "EstadoEnAlquiler" as eAlquiler

user -> gR : cerrarReserva(reserva)

activate gR
    gR -> res : getVehiculo()
    activate res
        res -->> gR : vehiculo
    deactivate res

    gR -> res : getGestionDelKilometraje().getTotalKmRecorridos()
    activate res
        res -> gK : getTotalKmRecorridos()
        activate gK
            gK -->> res : cantidadDeKilometrosRecorridos
        deactivate gK
        res -->> gR : cantidadDeKilometrosRecorridos
    deactivate res

'Finalizar Alquiler
    alt **[Estado es EstadoEnAlquiler]** (Bloque try)
        gR -> veh : finalizarAlquiler()
        activate veh
            veh -> veh : this.estado.finalizarAlquiler(this)
            Note right of veh : Estado actual es EstadoEnAlquiler
            veh -> eAlquiler : finalizarAlquiler(this)
            activate eAlquiler

                eAlquiler -> veh : incrementarAlquiler()
                activate veh
                deactivate veh

                eAlquiler -> veh : necesitaMantenimiento()
                activate veh
                    veh -> vMant : necesitaMantenimiento(contadorKm)
                    activate vMant
                        vMant -->> veh : boolean
                    deactivate vMant
                    veh -->> eAlquiler : boolean
                deactivate veh


                alt [(true) (Necesita Mantenimiento)]
                    eAlquiler -> veh : setEstado(new EstadoMantenimiento())
                    activate veh
                    deactivate veh

                    eAlquiler -> veh : resetearValoresMantenimiento()
                    activate veh
                        veh -> vMant : resetearValoresMantenimiento()
                        activate vMant
                        deactivate vMant
                    deactivate veh
                end
            deactivate eAlquiler
        
        deactivate veh

    else **[Otro Estado]** (Bloque catch)
        gR -> veh : finalizarAlquiler()
        activate veh
            Note over veh: Estado actual lanza la Excepción ErrorEstadoIncorrecto
            veh --x gR : Lanza Error
        deactivate veh
        Note over gR: Se captura el error
        gR --x user : throw error (Re-lanzamiento)
    end

    ' Calcular Costo Total
    gR -> res : calcularCostoTotal()
    activate res
        res -> gK : getInformacionDelRecorrido()
        activate gK
            gK -->> res : RegistroDia[]
        deactivate gK

        res -> gT : getTemporada(fechaInicioReserva)
        activate gT
            gT -->> res : TemporadaBase
        deactivate gT

        res -> veh : calcularTarifa(informacionRecorrido, temporada)
        activate veh
            veh -->> res : costoTotal
        deactivate veh

        res -->> gR : costoTotal
    deactivate res

    gR -->> user : costoTotal

deactivate gR

@enduml