@startuml Cerrar Reserva
title Diagrama de Secuencia: Cerrar Reserva

actor Cliente as user
participant "GestorDeReservas" as gR
participant "Reserva" as res
participant "GestorDeTemporada" as gT
participant "GestorKilometraje" as gK
participant "VehiculoMantenimiento" as vMant
participant "Vehiculo" as veh
participant "GestorDeMantenimiento" as gM
participant "MantenimientoVehiculo" as mant

user -> gR : cerrarReserva(reserva)

activate gR
    gR -> res : getVehiculo()
    activate res
        res --> gR : vehiculo
    deactivate res

    gR -> res : getGestionDelKilometraje()
    activate res
        res --> gR : GestorKilometraje
    deactivate res

    gR -> gK : getTotalKmRecorridos()
    activate gK
        gK --> gR : cantidadDeKilometrosRecorridos
    deactivate gK

    ' Actualizar KM y Mantenimiento
    gR -> veh : actualizarKMRecorridos(cantidadDeKilometrosRecorridos)
    activate veh
        veh -> veh : getContadorKm()
        activate veh
            veh --> veh : contadorKm
        deactivate veh
        veh -> veh : setContadorKm(contadorKm + cantidadDeKilometrosRecorridos)
    deactivate veh

    gR -> gM : procesarMantenimiento(vehiculo)
    activate gM
        gM -> veh : incrementarAlquiler()
        activate veh
            veh -> vMant: incrementarAlquiler()
        deactivate veh

        gM -> veh : necesitaMantenimiento()
        activate veh
            veh -> vMant : necesitaMantenimiento(contadorKm)
            activate vMant
                vMant --> veh : boolean
            deactivate vMant
            veh --> gM : boolean (true/false)
        deactivate veh

        alt Si necesita mantenimiento (true)
            gM -> veh : setEstado(EstadoVehiculo.EnMantenimiento)
            activate veh
            deactivate veh
            
            gM -> gM : registrarMantenimiento(vehiculo) ' <<Crea y configura el MantenimientoVehiculo>>
            activate gM
                create mant
                gM -> mant **: new()
                activate mant
                    mant -> mant : setFechaMantenimiento(new Date())
                    mant -> mant : setVehiculo(Vehiculo)
                deactivate mant
                gM -> gM : <<añade a array de vehiculosEnMantenimiento>>
            deactivate gM

            gM -> veh : resetearValoresMantenimiento()
            activate veh
                veh -> vMant: resetearValores()
                activate vMant
                deactivate vMant
            deactivate veh
        end

    deactivate gM

    ' Calcular Costo Total
    gR -> res : calcularCostoTotal()
    activate res
        res -> gK : getInformacionDelRecorrido()
        activate gK
            gK --> res : RegistroDia[]
        deactivate gK

        res -> gT : getTemporada(fechaInicioReserva)
        activate gT
            gT --> res : TemporadaBase
        deactivate gT

        res -> veh : calcularTarifa(informacionRecorrido, temporada)
        activate veh
            veh --> res : costoTotal
        deactivate veh

        res --> gR : costoTotal
    deactivate res

    gR --> user : costoTotal
deactivate gR

@enduml