@startuml TP

title "Drivehub"
scale 1.3

' Vehiculos
abstract class Vehiculo{
   -matricula: string
   -estado: string
   -contadorKm: number
   -tarifaBase: number
   -tarifaExtra: number

   + abstract calcularTarifa(fechaInicio: Date, fechaFinal: Date, kmRecorridos: number): number
   + actualizarContador(): void
   + setters_y_getters()
}

class Compacto{
   -tarifaBase: number
   -tarifaExtra: number
   + calcularTarifa(fechaInicio, fechaFinal, kmRecorridos): number
}

class Suv{
   -tarifaBase: number
   -tarifaExtra: number
   + calcularTarifa(fechaInicio, fechaFinal, kmRecorridos): number
}

class Sedan{
   -tarifaBase: number
   -tarifaExtra: number
   + calcularTarifa(fechaInicio, fechaFinal, kmRecorridos): number
}

Vehiculo <|-- Compacto
Vehiculo <|-- Sedan
Vehiculo <|-- Suv

' Clientes
class Cliente{
   -nombre: string
   -apellido: string
   -email: string
   
   + setters_y_getters()
}

class GestionDeClientes{
   - clientes: Cliente[]
   + agregarCliente(cliente: Cliente): void
   + eliminarCliente(cliente: Cliente): void
   - clienteExiste(cliente: Cliente): boolean
}

GestionDeClientes *-- Cliente

' Reservas
class Reserva{
   -cliente: Cliente
   -vehiculo: Vehiculo
   -fechaInicio: Date
   -fechaFinal: Date

   + calcularCostoTotal()
}

class GestionDeReservas{
   -chequearDisponibilidad(): void
   -reservas: Reserva[]
   +agregarReserva(reserva: Reserva): void
   +cerrarReserva(reserva: Reserva, kmRecorridos: number): number
}

GestionDeReservas *-- Reserva
Cliente *-- Reserva
Vehiculo *-- Reserva

' Vehiculos gestion
class GestionDeVehiculos{
   - vehiculos: Vehiculo[]
   + agregarVehiculo(vehiculo: Vehiculo): void
}

GestionDeVehiculos *-- Vehiculo

' Gestor principal
class GestorDeAlquilerVehicular{
   - gestionDeVehiculos: GestionDeVehiculos
   - gestionDeClientes: GestionDeClientes
   - gestionDeReservas: GestionDeReservas
}

GestorDeAlquilerVehicular o-- GestionDeVehiculos 
GestorDeAlquilerVehicular o-- GestionDeReservas
GestorDeAlquilerVehicular o-- GestionDeClientes

' Mantenimiento
class MantenimientoVehiculo{
   -fechaMantenimiento: Date
   -costo: number
   -modelo: string
   + setters_y_getters()
}

class GestorDeMantenimiento{
   - vehiculosEnMantenimiento: MantenimientoVehiculo[]
   + registrarMantenimiento(vehiculo: MantenimientoVehiculo) : void
}

GestorDeMantenimiento o-- MantenimientoVehiculo

' Dep
